version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest  # Puedes actualizar a la última versión estable
    container_name: qdrant
    ports:
      - "6333:6333"    # API REST y gRPC
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped