version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:v1.15.2
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:6333/"]
      interval: 10s
      timeout: 3s
      retries: 10